spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/balance_control
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: true
  jackson:
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: non_null
    deserialization:
      fail-on-unknown-properties: false
  flyway:
    url: jdbc:mariadb://localhost:3306/balance_control
    user: root
    password: root
    baseline-on-migrate: true
