spring:
  datasource:
    url: ${BC_DB_URL:jdbc:mariadb://localhost:3306/balance_control?createDatabaseIfNotExist=true}
    username: ${BC_DB_USER:root}
    password: ${BC_DB_PASS:root}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: true
  jackson:
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: non_null
    deserialization:
      fail-on-unknown-properties: false
  flyway:
    url: ${BC_DB_URL:jdbc:mariadb://localhost:3306/balance_control?createDatabaseIfNotExist=true}
    user: ${BC_DB_USER:root}
    password: ${BC_DB_PASS:root}
    baseline-on-migrate: true
